### ISSUE TITLE
Node 0.12 compatibility

### ISSUE THREAD

**Issue by Spechal** [codeforkansascity/meep#66]
The core-util-is NPM package needs to be added and then Node 0.12 looks to be supported in the codebase.

Without core-util-is:
```
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '/usr/src/app/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by Spechal** [comment]
Taken care of in #67
